### ISSUE TITLE
Values are not delivered in configured language - only english

### ISSUE THREAD

**Issue by Loxfreek** [oklona/Miele-MQTT#27]
Hi, the actual script is only transfering the values in english. If I have setup my config for "de-DE" still the transmitted data to MQTT-Gateway is in english (like Device typ Oven instead of Backofen).

**Miele API offers the language setting:**
curl -H "Accept:text/event-stream" -H "Accept-Language: {{de-DE||en-GB}}" -H "Authorization: Bearer {{access_token}}" https://api.mcs3.miele.com/v1/devices/all/events

[Quelle: https://www.miele.com/developer/eventing.html]

It would be good if the script could use the accepted language value to transmit values in configured language.

**Comment by oklona** [comment]
Interesting. I will be away for a couple of weeks, but will try to look into it. 
    	
    
  

 Fra: Loxfreek ***@***.***>Sendt: søndag, juli 18, 2021 10:20 amTil: oklona/Miele-MQTTKopi: SubscribedEmne: [oklona/Miele-MQTT] Values are not delivered in configured language - only english (#27) 
Hi, the actual script is only transfering the values in english. If I have setup my config for "de-DE" still the transmitted data to MQTT-Gateway is in english (like Device typ Oven instead of Backofen).
Miele API offers the language setting:
curl -H "Accept:text/event-stream" -H "Accept-Language: {{de-DE||en-GB}}" -H "Authorization: Bearer {{access_token}}" https://api.mcs3.miele.com/v1/devices/all/events
[Quelle: https://www.miele.com/developer/eventing.html]
It would be good if the script could use the accepted language value to transmit values in configured language.

**Comment by christianTF** [comment]
I have got yesterday (not joking) a new Miele Dish Washer with Miele@Home.

I will give the language selection by Accept-Language a try in your code, and will submit a pull request if it is working.

cu, Christian

![image](https://user-images.githubusercontent.com/14220265/126312494-843b1820-fe17-4910-8623-eb9a249658ca.png)

**Comment by Loxfreek** [comment]
Looking forward. 
Christian, this only helps me when my script will run again automatically. I’ve sent you a PM

Viele Grüße 
Winterholler Jürgen

**Comment by christianTF** [comment]
I've tried the `Accept-Language` header, but this is not working.

Instead, it requires a language=xx parameter in the API url, like
`curl https://api.mcs3.miele.com/v1/devices?language=de`

This will give German texts:
![image](https://user-images.githubusercontent.com/14220265/126363407-92c87d66-8cfd-4e3f-8228-0d6dc557fb14.png)

I've tried en de fr es, that are working, but not every language is supported (for example cz or cs are not working).
