### ISSUE TITLE
Script errors and miele-config.php.org

### ISSUE THREAD

**Issue by ChutneyMary** [oklona/Miele-MQTT#5]
In the last 1-2 weeks, the script has stopped working. I note that the Miele folder has a new file called miele-config.php.org. This file has both the Access token and Refresh token. The old file (miele-config.php) is missing the tokens.

Running the script from scratch (before the config file is generated), causes an error -

PHP Notice: Undefined variable: data in /opt/loxberry/webfrontend/legacy/miele/miele-MQTT.php on line 253 
PHP Warning: Invalid argument for foreach () in /opt/loxberry/webfrontend/legacy/miele/miele-MQTT.php on line 253 

or a different variation;

PHP Notice: Undefined variable: data at /opt/loxberry/webfrontend/legacy/miele/miele-MQTT.php on line 229 
PHP Warning: Invalid argument for foreach () in / opt / loxberry / webfrontend / legacy / miele / miele -MQTT.php on line 229 

There was also a third variation with a different line number error.

**Comment by oklona** [comment]
Yes, I have noticed this. I tried to debug the logon process, and it seems we are getting a 401-Unauthorized  - message when trying to access data with a newly generated token. I don't know whether this is caused by issues at Miele, or if they have just changed behavior. I asked Miele to verify whether my client ID and secret had been changed, but never received a reply. I will be trying again at a later point, when I find time.

**Comment by oklona** [comment]
Great news!! Since Miele released v. 1.0 of their API today, the script is working again. No changes from my side of things. This also means that we can expect it to be relatively stable now, since v 1.0 is supposed to be a stable version of the API :-)
